<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS0Xf3Gf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS0Xf3Gf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerS0Xf3Gf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerS0Xf3Gf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerS0Xf3Gf\App_KernelDevDebugContainer([
    'container.build_hash' => 'S0Xf3Gf',
    'container.build_id' => '3ef7f2bb',
    'container.build_time' => 1697186390,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerS0Xf3Gf');
