<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container79NVuMA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container79NVuMA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container79NVuMA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container79NVuMA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container79NVuMA\App_KernelDevDebugContainer([
    'container.build_hash' => '79NVuMA',
    'container.build_id' => '64e30e45',
    'container.build_time' => 1698222202,
], __DIR__.\DIRECTORY_SEPARATOR.'Container79NVuMA');
