<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_xdebug' => [[], ['_controller' => 'web_profiler.controller.profiler::xdebugAction'], [], [['text', '/_profiler/xdebug']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    'insertar_cancion' => [[], ['_controller' => 'App\\Controller\\MusicController::insertar'], [], [['text', '/music/insertar']], [], [], []],
    'insertar_cancion_con_artista' => [[], ['_controller' => 'App\\Controller\\MusicController::insertarConProvincia'], [], [['text', '/music/insertarConArtista']], [], [], []],
    'insertar_cancion_sin_provincia' => [[], ['_controller' => 'App\\Controller\\MusicController::insertarSinProvincia'], [], [['text', '/music/insertarSinArtista']], [], [], []],
    'nuevo_cancion' => [[], ['_controller' => 'App\\Controller\\MusicController::nuevo'], [], [['text', '/music/nuevo']], [], [], []],
    'editar_cancion' => [['codigo'], ['_controller' => 'App\\Controller\\MusicController::editar'], [], [['variable', '/', '[^/]++', 'codigo', true], ['text', '/music/editar']], [], [], []],
    'eliminar_cancion' => [['id'], ['_controller' => 'App\\Controller\\MusicController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/music/delete']], [], [], []],
    'app_music' => [[], ['_controller' => 'App\\Controller\\MusicController::index'], [], [['text', '/music']], [], [], []],
    'ficha_cancion' => [['codigo'], ['_controller' => 'App\\Controller\\MusicController::ficha'], [], [['variable', '/', '[^/]++', 'codigo', true], ['text', '/music']], [], [], []],
    'buscar_cancion' => [['texto'], ['_controller' => 'App\\Controller\\MusicController::buscar'], [], [['variable', '/', '[^/]++', 'texto', true], ['text', '/music/buscar']], [], [], []],
    'modificar_contacto' => [['id', 'nombre'], ['_controller' => 'App\\Controller\\MusicController::update'], [], [['variable', '/', '[^/]++', 'nombre', true], ['variable', '/', '[^/]++', 'id', true], ['text', '/music/update']], [], [], []],
    'app_page' => [[], ['_controller' => 'App\\Controller\\PageController::index'], [], [['text', '/page']], [], [], []],
    'inicio' => [[], ['_controller' => 'App\\Controller\\PageController::inicio'], [], [['text', '/']], [], [], []],
];
